### GET ALL BLOGS, GET/blogs
GET http://localhost:3000/blogs

### GET SPECIFIED BLOG, GET/blogs/:id
GET http://localhost:3000/blogs/2

### CREATE A NEW BLOG, POST/blogs
POST http://localhost:3000/blogs
Content-Type: application/json

{
    "text" : ""
}

### UPDATE A BLOG, PATCH/blogs/:id
PATCH http://localhost:3000/blogs/5
Content-Type: application/json

{
    "text": "Now I'm pretty sure everything working correctly! I guess :/"
}

### DELETE A BLOG, DELETE/blogs/:id
DELETE http://localhost:3000/blogs/5